server:
  port : 8081

spring:
  main:
    banner-mode: "off"
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  data:
    mongodb:
      database: archive

alfresco:
  repository:
    url: http://localhost:8080/alfresco
    user: admin
    pass: admin
